import { Link } from 'react-router-dom'
import LegalPage from './LegalPage'

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms & Conditions"
      path="/terms"
      description="The terms and conditions that govern your use of the Pāvati Pustak platform."
      updated="October 2026"
    >
      <p>
        These Terms & Conditions ("Terms") govern your use of Pāvati Pustak ("we", "us", "our"), a digital
        trust, donation and receipt management platform. By creating an account or using the Service, you agree
        to these Terms. If you do not agree, please do not use the Service.
      </p>

      <h2 className="pt-4 text-xl font-bold text-stone-900">1. Your account</h2>
      <ul className="list-disc space-y-2 pl-6">
        <li>You must provide accurate information and keep your credentials confidential.</li>
        <li>You are responsible for all activity under your account.</li>
        <li>You must be at least 18 years old, or use the Service with the authorisation of your trust or organisation.</li>
        <li>Notify us immediately at{' '}
          <a href="mailto:support@pavatipustak.app" className="font-semibold text-saffron-600 hover:underline">
            support@pavatipustak.app
          </a> if you suspect unauthorised access to your account.
        </li>
      </ul>

      <h2 className="pt-4 text-xl font-bold text-stone-900">2. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul className="list-disc space-y-2 pl-6">
        <li>Use the Service for any unlawful, fraudulent, or misleading purpose.</li>
        <li>Record donations or donor information you are not authorised to handle.</li>
        <li>Attempt to access other trusts' data, probe security, or disrupt the Service.</li>
        <li>Upload content that infringes the rights of others or violates applicable law.</li>
        <li>Resell or sublicense the Service without our written consent.</li>
      </ul>

      <h2 className="pt-4 text-xl font-bold text-stone-900">3. Trust and donation data</h2>
      <p>
        You are responsible for the accuracy of the trust profile, donation records, and receipts you create.
        Receipts generated by the Service are records of the information you or your trust enter; they are not
        financial, tax, or legal advice. Consult a qualified professional for compliance with local regulations.
      </p>

      <h2 className="pt-4 text-xl font-bold text-stone-900">4. Intellectual property</h2>
      <p>
        The Service, including its software, design, and branding, is owned by us and protected by applicable
        intellectual property laws. You retain ownership of the content you upload (logos, templates, donation
        data) and grant us a limited licence to host and process it solely to provide the Service.
      </p>

      <h2 className="pt-4 text-xl font-bold text-stone-900">5. Suspension and termination</h2>
      <p>
        You may stop using the Service at any time and request account deletion. We may suspend or terminate
        accounts that violate these Terms, create risk for other users, or are required to be closed by law.
        Upon termination, we will delete or anonymise your data in accordance with our{' '}
        <Link to="/privacy" className="font-semibold text-saffron-600 hover:underline">Privacy Policy</Link>,
        except where retention is required by law.
      </p>

      <h2 className="pt-4 text-xl font-bold text-stone-900">6. Disclaimers</h2>
      <p>
        The Service is provided "as is" and "as available" without warranties of any kind, express or implied,
        including warranties of merchantability, fitness for a particular purpose, and non-infringement. We do
        not warrant that the Service will be uninterrupted, error-free, or completely secure.
      </p>

      <h2 className="pt-4 text-xl font-bold text-stone-900">7. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special,
        consequential, or punitive damages, or any loss of data, revenue, or goodwill, arising from your use of
        the Service.
      </p>

      <h2 className="pt-4 text-xl font-bold text-stone-900">8. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. Material changes will be announced through the Service.
        Continued use after changes means you accept the updated Terms.
      </p>

      <h2 className="pt-4 text-xl font-bold text-stone-900">9. Contact</h2>
      <p>
        Questions about these Terms? <Link to="/contact" className="font-semibold text-saffron-600 hover:underline">Contact us</Link>{' '}
        or email{' '}
        <a href="mailto:support@pavatipustak.app" className="font-semibold text-saffron-600 hover:underline">
          support@pavatipustak.app
        </a>.
      </p>
    </LegalPage>
  )
}
