import { ROLE, type TrustRole } from './constants.js'

export const PERMISSION = {
  TRUST_VIEW: 'trust:view',
  TRUST_UPDATE: 'trust:update',
  TRUST_DELETE: 'trust:delete',
  MEMBER_VIEW: 'member:view',
  MEMBER_INVITE: 'member:invite',
  MEMBER_ADD: 'member:add',
  MEMBER_MANAGE_ROLES: 'member:manage_roles',
  MEMBER_REMOVE: 'member:remove',
  DONATION_VIEW: 'donation:view',
  DONATION_CREATE: 'donation:create',
  DONATION_REFUND: 'donation:refund',
  DONATION_VOID: 'donation:void',
  DONATION_VERIFY: 'donation:verify',
  DONATION_VIEW_OWN: 'donation:view_own',
  RECEIPT_CREATE: 'receipt:create',
  RECEIPT_VIEW: 'receipt:view',
  RECEIPT_REPRINT: 'receipt:reprint',
  RECEIPT_VOID: 'receipt:void',
  TEMPLATE_MANAGE: 'template:manage',
  CAMPAIGN_MANAGE: 'campaign:manage',
  CAMPAIGN_VIEW: 'campaign:view',
  ANNOUNCEMENT_CREATE: 'announcement:create',
  ANNOUNCEMENT_UPDATE: 'announcement:update',
  ANNOUNCEMENT_DELETE: 'announcement:delete',
  ANNOUNCEMENT_PIN: 'announcement:pin',
  ANNOUNCEMENT_VIEW: 'announcement:view',
  REPORT_VIEW: 'report:view',
  SETTINGS_UPDATE: 'settings:update',
  NOTIFICATION_MANAGE: 'notification:manage',
  AUDIT_VIEW: 'audit:view',
  DONATE: 'donate',
  MEMBER_VIEW_OWN: 'member:view_own',
} as const
export type Permission = (typeof PERMISSION)[keyof typeof PERMISSION]

export const ALL_PERMISSIONS = Object.values(PERMISSION) as Permission[]

export const OFFICIAL_ROLES: TrustRole[] = [
  ROLE.PRIMARY_ADMIN,
  ROLE.ADMIN,
  ROLE.PRESIDENT,
  ROLE.VICE_PRESIDENT,
  ROLE.SECRETARY,
  ROLE.JOINT_SECRETARY,
  ROLE.TREASURER,
  ROLE.COMMITTEE_MEMBER,
]

const everyone: Permission[] = [
    PERMISSION.TRUST_VIEW,
    PERMISSION.ANNOUNCEMENT_VIEW,
    PERMISSION.DONATE,
    PERMISSION.DONATION_VIEW_OWN,
    PERMISSION.RECEIPT_VIEW,
    PERMISSION.CAMPAIGN_VIEW,
    PERMISSION.MEMBER_VIEW_OWN,
  ]

const ops: Permission[] = [
  PERMISSION.DONATION_CREATE,
  PERMISSION.RECEIPT_CREATE,
  PERMISSION.RECEIPT_REPRINT,
  PERMISSION.ANNOUNCEMENT_VIEW,
]

export const ROLE_PERMISSIONS: Record<TrustRole, Permission[]> = {
  [ROLE.PRIMARY_ADMIN]: ALL_PERMISSIONS,
  [ROLE.ADMIN]: [
    PERMISSION.TRUST_VIEW,
    PERMISSION.TRUST_UPDATE,
    PERMISSION.MEMBER_VIEW,
    PERMISSION.MEMBER_INVITE,
    PERMISSION.MEMBER_ADD,
    PERMISSION.MEMBER_MANAGE_ROLES,
    PERMISSION.MEMBER_REMOVE,
    PERMISSION.DONATION_VIEW,
    PERMISSION.DONATION_CREATE,
    PERMISSION.DONATION_REFUND,
    PERMISSION.DONATION_VOID,
    PERMISSION.DONATION_VERIFY,
    PERMISSION.RECEIPT_CREATE,
    PERMISSION.RECEIPT_VIEW,
    PERMISSION.RECEIPT_REPRINT,
    PERMISSION.RECEIPT_VOID,
    PERMISSION.TEMPLATE_MANAGE,
    PERMISSION.CAMPAIGN_MANAGE,
    PERMISSION.CAMPAIGN_VIEW,
    PERMISSION.ANNOUNCEMENT_CREATE,
    PERMISSION.ANNOUNCEMENT_UPDATE,
    PERMISSION.ANNOUNCEMENT_DELETE,
    PERMISSION.ANNOUNCEMENT_PIN,
    PERMISSION.ANNOUNCEMENT_VIEW,
    PERMISSION.REPORT_VIEW,
    PERMISSION.SETTINGS_UPDATE,
    PERMISSION.NOTIFICATION_MANAGE,
    PERMISSION.AUDIT_VIEW,
    PERMISSION.DONATE,
    PERMISSION.MEMBER_VIEW_OWN,
  ],
  [ROLE.PRESIDENT]: [
    ...everyone,
    ...ops,
    PERMISSION.DONATION_VIEW,
    PERMISSION.MEMBER_VIEW,
    PERMISSION.REPORT_VIEW,
    PERMISSION.ANNOUNCEMENT_CREATE,
    PERMISSION.CAMPAIGN_VIEW,
  ],
  [ROLE.VICE_PRESIDENT]: [
    ...everyone,
    ...ops,
    PERMISSION.DONATION_VIEW,
    PERMISSION.MEMBER_VIEW,
    PERMISSION.REPORT_VIEW,
    PERMISSION.ANNOUNCEMENT_CREATE,
  ],
  [ROLE.SECRETARY]: [
    ...everyone,
    ...ops,
    PERMISSION.DONATION_VIEW,
    PERMISSION.MEMBER_VIEW,
    PERMISSION.MEMBER_INVITE,
    PERMISSION.MEMBER_ADD,
    PERMISSION.ANNOUNCEMENT_CREATE,
    PERMISSION.ANNOUNCEMENT_UPDATE,
    PERMISSION.ANNOUNCEMENT_DELETE,
    PERMISSION.ANNOUNCEMENT_PIN,
  ],
  [ROLE.JOINT_SECRETARY]: [...everyone, ...ops, PERMISSION.DONATION_VIEW, PERMISSION.MEMBER_VIEW, PERMISSION.ANNOUNCEMENT_CREATE],
  [ROLE.TREASURER]: [
    ...everyone,
    ...ops,
    PERMISSION.DONATION_VIEW,
    PERMISSION.REPORT_VIEW,
    PERMISSION.DONATION_REFUND,
    PERMISSION.DONATION_VOID,
    PERMISSION.DONATION_VERIFY,
    PERMISSION.RECEIPT_VOID,
  ],
  [ROLE.COMMITTEE_MEMBER]: [...everyone, ...ops, PERMISSION.DONATION_VIEW, PERMISSION.MEMBER_VIEW, PERMISSION.REPORT_VIEW],
  [ROLE.MEMBER]: everyone,
  [ROLE.VOLUNTEER]: everyone,
  [ROLE.COLLECTOR]: [PERMISSION.DONATION_CREATE, PERMISSION.RECEIPT_CREATE, PERMISSION.RECEIPT_VIEW, PERMISSION.RECEIPT_REPRINT, PERMISSION.TRUST_VIEW, PERMISSION.ANNOUNCEMENT_VIEW, PERMISSION.DONATE, PERMISSION.MEMBER_VIEW_OWN, PERMISSION.CAMPAIGN_VIEW],
}

export function permissionsForRole(role: TrustRole): Permission[] {
  return ROLE_PERMISSIONS[role] ?? everyone
}

export const PERMISSION_LABELS: Record<Permission, string> = {
  'trust:view': 'View trust',
  'trust:update': 'Update trust settings',
  'trust:delete': 'Delete trust',
  'member:view': 'View members',
  'member:invite': 'Invite members',
  'member:add': 'Add members',
  'member:manage_roles': 'Manage roles & permissions',
  'member:remove': 'Remove members',
  'donation:view': 'View donations',
  'donation:create': 'Create donations',
  'donation:refund': 'Refund donations',
  'donation:void': 'Void donations',
  'donation:view_own': 'View own donations',
  'receipt:create': 'Create receipts',
  'receipt:view': 'View receipts',
  'receipt:reprint': 'Reprint receipts',
  'receipt:void': 'Void receipts',
  'template:manage': 'Manage receipt templates',
  'campaign:manage': 'Manage payment campaigns',
  'campaign:view': 'View campaigns',
  'announcement:create': 'Create announcements',
  'announcement:update': 'Edit announcements',
  'announcement:delete': 'Delete announcements',
  'announcement:pin': 'Pin announcements',
  'announcement:view': 'View announcements',
  'report:view': 'View reports',
  'settings:update': 'Update trust settings',
  'notification:manage': 'Manage notifications',
  'audit:view': 'View audit log',
  'donation:verify': 'Verify UPI payments',
  donate: 'Make donations',
  'member:view_own': 'View own membership',
}